name: Docker Image CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build the Docker image
      env:
        IMAGE_TAG: v1.0
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/video-search-prediction-opt:$IMAGE_TAG

    - name: Push to DockerHub
      env:
        IMAGE_TAG: v1.0
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/video-search-prediction-opt:$IMAGE_TAG

    - name: Logout from DockerHub
      run: docker logout
